name: Testing on push

on: push

jobs:
  test:
    name: Test passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install modules
        run: npm ci

      - name: Unit / Component testing
        run: npm run test:unit

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev
